### ISSUE TITLE
dock audio

### ISSUE THREAD

**Issue by Kustomz** [teamacid/android_device_samsung_galaxys4gmtd#21]
dock audio not working with cm7 or cm9

**Comment by maxfierke** [comment]
Have you tried the newest build of CM9?

**Comment by maxfierke** [comment]
It's been reported this has been fixed in CM9/AOKP.

**Comment by Kustomz** [comment]
still not working on my end. might be my device/dock though. not sure since it does change the display when in dock mode. idk -shrug-
